### ISSUE TITLE
particulate composite microstructure 

### ISSUE THREAD

**Issue by tarkesdora** [Mote3D/Mote3D_toolbox#7]
I tried to create a particulate composite microstructure with a variance of diameter as zero (eg picture as shown in the first page github  MOTE3D) by merging with a cube. I face merge error always. I tried with vol fraction of 0.1 and 0.25. Any help or directions I should try in this regard would be useful. Generating a porous microstructure is very easy by using cut option of ABAQUS in the assembly module.

_Originally posted by @tarkesdora in https://github.com/Mote3D/Mote3D_toolbox/issues/6#issuecomment-798158438_

**Comment by Mote3D** [comment]
Which particle overlap factor do you use? Did you try to subtract ("cut") the particles from the solid cube first and then merge the particles with the remaining skeleton of the cube?

**Comment by tarkesdora** [comment]
Particle overlap factor is 1(no overlap). Yes I tried that out but doesn't help. Some more additional concerns:
1. I didn't have a deep look into the algorithm but I don't understand the reason behind the "agglomeration" of particles takes place near the corner of the cube despite there is more space inside the cube (atleast for lower number of particles 20 lets say). This leads to issue definitely on mesh quality and maybe I guess merging of geometry in ABAQUS. I was successful at least creating the geometry and mesh using CSG() of NETGEN. 
2. Also if I am correct, it seems the number of particles is counted as the number of parts of the sphere present inside the cube and not the complete sphere as 1 particle which leads to an undesirable volume fraction.

**Comment by Mote3D** [comment]
If the actual microstructure you intend to model permits, you could try to increase the particle overlap factor slightly, let's say to 1.1. This usually helps to avoid problems with Boolean merge operations in ABAQUS.

The "agglomeration" happens due to particle translations that are carried out to increase packing density. This feature can be turned off in the next release.

Particle counting considers the periodicity of the modelling domain, i.e. the particle number is the total number of particles that are entirely or partly inside the domain. A mass/volume properties query in ABAQUS can be used to determine the corresponding particle volume fraction.
